"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

set t_Co=256

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  filetype off
  set rtp+=~/.vim/bundle/Vundle.vim/
  call vundle#rc()
 
  " Override default colorscheme
  let g:dotvim_colorscheme='torte'

  " See ~/.vim/vundles.vim for various groups you can enable
  let g:vundles=['general', 'programming', 'completion', 'python', 'misc']

  " Load 'vundles'
  source ~/.vim/vundles.vim

  " Add extra bundles here...
  " Bundle 'reponame'

  let g:neocomplcache_enable_at_startup = 1
endif
